### PR TITLE
Replaces 'rm -rf' with rimraf

### LINKED ISSUE #218: Using rimraf instead of `rm -rf` for cleaning a directory in scripts
#### This issue pertains to:

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground

We should change this `rm -rf` which is in several NPM scripts in the playground (i.e. `"build": "rm -rf lib &&...`) to use `rimraf` which is a cross-platform compatible solution.

This is necessary for Windows users to be able to contribute to this project.

### PR DESCRIPTION
**Pull request by DevanB**
Fixes #218.

Looks like my local prettier cleaned up the electron app `package.json`. If you want me to turn it off, clean up the PR, and resubmit, let me know!

### CODE REVIEW

**Comment by kbrandwijk** [comment]
Having rimraf as a dependency will still not work on windows, because only globally installed modules are available as CLI commands. If the scripts could use `./node_modules/.bin/rimraf ...` it would work really well (I'm doing the same for `ts-node` for example in my projects, when not installed globally).

**Comment by DevanB** [comment]
@kbrandwijk As I understand it, when evaluating scripts, npm adds `node_modules/.bin/` to the PATH environment variable. That means you can forego the folder prefix.

Here is a reference, which I may be interpreting incorrectly: http://2ality.com/2016/01/locally-installed-npm-executables.html

**Comment by kbrandwijk** [comment]
@DevanB I never knew, and I just tested it. And it works beautifully, even with something like nodemon in your scripts. Thanks for sharing!

**Comment by schickling** [comment]
Thanks a lot @DevanB :)

**Pull request merged**
