### PR TITLE
WIP: feat: migrate to apollo link as a network transport

### PR DESCRIPTION
**Pull request by DavidJFelix**
# WIP
**I don't think this is functional yet**
**Expect changes and rebases on remote repo**

Make changes described in #195 

There is some additional cleanup effort occurring here.

- Move from rxjs/Observable to zen-observable.
  This is the type of Observable that apollo-link naturally returns
- Align fetch() code to use apollo-link-http to simplify fetcher and make #195 easier to implement
- minor TS typing improvements

### CODE REVIEW

**Comment by DavidJFelix** [comment]
Opening this PR for transparency on my intended changes so I don't refactor too much without opinions.

**Comment by timsuchanek** [comment]
Thanks for the PR @DavidJFelix !
This is very much the right direction, we wanted to include Apollo Link for quite some time now.
Is there anything missing from your view in this PR?

**Comment by DavidJFelix** [comment]
@timsuchanek yeah. it still doesn't work. I'm working on refactoring the fetcher right now... its just very tightly coupled with several large components and i'm trying to rewire it with the new apollo link. I'll remove the WIP and @ mention you when it's done.

**Comment by timsuchanek** [comment]
Ok awesome. Please note that we right now have 2 fetchers, one in `Playground` and one in `SchemaFetcher`. So `SchemaFetcher` would need to get that as a prop, too.

**Comment by DavidJFelix** [comment]
Good call out. I'll make sure I get schemafetcher patched. Like I said, still poking around trying to fully absorb all of the state changes that happen within these huge components and what each prop does.

**Pull request merged**
