### PR TITLE
Add GraphQL file association

### LINKED ISSUE #50: .graphql files should automatically open with GP

### PR DESCRIPTION
**Pull request by slashmo**
Adds the file association for GraphQL files to allow users to double-click to open a file.

Tested on macOS High Sierra

Closes #50

### CODE REVIEW

**Comment by kbrandwijk** [comment]
There should be an option in the setup as well if you're doing file associations. I want to open .graphql files in my editor, not in the playground by default.

**Comment by slashmo** [comment]
@kbrandwijk Thanks for the suggestion! 👍 Isn't that part of the operating system? On macOS I can define the default application for opening a specific file type. As far as I know the file association just gives you the opportunity to open the file in the application, but doesn't require it if you set a different application as the default app.

**Comment by kbrandwijk** [comment]
@slashmo Yes, you can define the default operation in the OS. But it's kind of a best practice (at least on Windows) to not overwrite a user's default application without asking (usually during setup, or initial startup for apps without a setup).

**Comment by slashmo** [comment]
@kbrandwijk That's exactly my point: Does it really overwrite your exciting default? Or does it just give you the option to overwrite it if you want to? But I agree that it would be nice if you could switch the default while setting up the app in case you want to use GraphQL Playground as the default app.

**Comment by kbrandwijk** [comment]
On Windows, it would overwrite the existing default.

**Comment by slashmo** [comment]
Ah, okay. Didn't know that. Thanks for the heads up! 👍 I'll look into that.

**Comment by timsuchanek** [comment]
That's a good point @kbrandwijk. We should test how this affects Windows users. I'm merging this for now, so @slashmo can continue from there with the missing file opening logic (we still need to inject the context). But before we release this, we have to test it on Windows.

**Comment by kbrandwijk** [comment]
@timsuchanek I thought that was the whole idea of branching...

**Pull request merged**
