### PR TITLE
[WIP] Adds auto-updating using Hazel

### PR DESCRIPTION
**Pull request by DevanB**
See title :)

### CODE REVIEW

**Comment by DevanB** [comment]
@timsuchanek 

When I try to build the project, I receive the following errors:

```
✔ ~/Projects/graphql-playground/packages/graphql-playground-electron [master|✔]
21:46 $ npm run build

> playground@1.0.1 build /Users/devanbeitel/Projects/graphql-playground/packages/graphql-playground-electron
> npm run build-ts && npm run build-webpack && cp -r dist lib && rm -rf ./build-electron


> playground@1.0.1 build-ts /Users/devanbeitel/Projects/graphql-playground/packages/graphql-playground-electron
> rm -rf lib && tsc --target es5

src/ElectronApp.tsx(2,37): error TS2307: Cannot find module 'electron'.
src/ElectronApp.tsx(150,14): error TS2339: Property 'closeTab' does not exist on type 'Playground'.
src/InitialView/InitialView.tsx(3,24): error TS2307: Cannot find module 'electron'.
src/main.ts(3,80): error TS2307: Cannot find module 'electron'.
src/utils.ts(1,24): error TS2307: Cannot find module 'electron'.
src/utils.ts(5,31): error TS2503: Cannot find namespace 'Electron'.
```

Just leaving this here so maybe you can help me debug this. It may be another `tsconfig.json` change. Not sure.

**Comment by Huvik** [comment]
You need to link graphcool-playground, because its using version from npm.

**Comment by DevanB** [comment]
@Huvik thanks! @timsuchanek told me that just a day before. I'm going to add it to the README in this PR for others who might want to work/build the electron app :)

**Comment by timsuchanek** [comment]
Thanks for the PR! I will try it out right now :)

**Pull request merged**
